application: twixmit
version: 1
runtime: python
api_version: 1

handlers:
- url: /favicon\.ico
  static_files: static/noun_project_296_1.svg
  upload: static/noun_project_296_1.svg
  
- url: /static
  static_dir: static

- url: .*
  script: main.py
